print("Give me the first number")
numberOne = int(input())
print("Give me the second number")
numberTwo = int(input())
print(numberOne + numberTwo)
print(numberOne - numberTwo)
print(numberOne * numberTwo)
print(numberOne / numberTwo)
print(numberOne ** numberTwo)
print(numberOne // numberTwo)
print(numberOne % numberTwo)